title: Comunidade PHP Brasil
email: naotemos@nehumemail.com
description: > # this means to ignore newlines until "baseurl:"
  Se você conhece o Grupo de Telegram sabe que lá é correria!
  Com base nisso decidimos criar um blog com materiais que são comentados e discutidos por lá ;)
baseurl: "/blog"
url: "https://rafagouveia.github.io"
header-img: blog/assets/img/elephant.jpg
github_username:  rafagouveia
highlighter: rouge
permalink: pretty
paginate: 10
comments: true
disqus:
  shortname: https-rafagouveia-github-io-blog
exclude:
  - Gemfile
  - Gemfile.lock
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-paginate

